name: HGN-DGL
channels:
  - dglteam/label/th24_cu121
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=2.0.0=py39h4eded50_0
  - charset-normalizer=3.4.4=py39h06a4308_0
  - dgl=2.4.0.th24.cu121=py39_0
  - expat=2.7.3=h7354ed3_3
  - idna=3.11=py39h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_3
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.2.1=py39h06a4308_0
  - numpy=2.0.1=py39h5f9d8c6_1
  - numpy-base=2.0.1=py39hb5e798b_1
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - psutil=7.0.0=py39hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.23=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py39h06a4308_0
  - scipy=1.13.1=py39h5f9d8c6_1
  - setuptools=80.9.0=py39h06a4308_0
    - sqlite=3.51.0=h2a70700_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py39h2f386ee_0
  - urllib3=2.5.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - blis==1.3.3
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.13
      - en-core-web-sm==3.8.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.3
      - preshed==3.0.12
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - six==1.17.0
      - smart-open==7.5.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - sympy==1.13.1
      - thinc==8.3.9
      - tokenizers==0.21.4
      - torch==2.4.0+cu121
      - transformers==4.49.0
      - triton==3.0.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - wasabi==1.1.3
      - weasel==0.4.3
      - wrapt==2.0.1